config/routes.rb
Bianiapp::Application.routes.draw do
  
  devise_for :users

  resources :orders

  root :to => "orders#index"

  get "/calculator" => "orders#calculator"
  get "/product" => "orders#product"
  get "/persona" => "orders#persona"
  get "/wall" => "orders#wall"
  get "/distributor" => "orders#distributor"

  match "contact", to: "contact#contact", as: "contact"
  match "dispatch_email", to: "contact#dispatch_email", as: "dispatch_email", method: :post

  match "invoice", to: "contact#invoice", as: "invoice"
  match "invoicer_email", to: "contact#invoicer_email", as: "invoicer_email", method: :post

  

end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :height, :width
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def contact
  end


  def dispatch_email
    if params[:user_info][:nickname].blank? || params[:user_info][:nickname].nil? # Hidden parameter to check for spam
      if params[:user_info][:name].blank? || params[:user_info][:name].nil?
      	flash[:alert] = "Es necesario llenar todos los campos"
      elsif params[:user_info][:email].blank? || params[:user_info][:email].nil?
      	flash[:alert] = "Es necesario llenar todos los campos"
      elsif params[:user_info][:message].blank? || params[:user_info][:message].nil?
      	flash[:alert] = "Es necesario llenar todos los campos"
      else
      	user_info = params[:user_info]
      	if BianiMailer.contact_mail(user_info).deliver
        	flash[:notice] = "Mensaje enviado correctamente, en bereve nos comunicaremos contigo"
      	else
        	flash[:notice] = "Oops"
      	end
      end
    else
      flash[:alert] = "Spam"
    end
    redirect_to contact_url
  end

  def invoice
  end


  def invoicer_email
    if params[:user_info][:nickname].blank? || params[:user_info][:nickname].nil? # Hidden parameter to check for spam
      if params[:user_info][:name].blank? || params[:user_info][:name].nil?
        flash[:alert] = "Es necesario llenar todos los campos"
      elsif params[:user_info][:email].blank? || params[:user_info][:email].nil?
        flash[:alert] = "Es necesario llenar todos los campos"
      elsif params[:user_info][:message].blank? || params[:user_info][:message].nil?
        flash[:alert] = "Es necesario llenar todos los campos"
      else
        user_info = params[:user_info]
        if BianiMailer.invoice_mail(user_info).deliver
          flash[:notice] = "Mensaje enviado correctamente, en bereve nos comunicaremos contigo"
        else
          flash[:notice] = "Oops"
        end
      end
    else
      flash[:alert] = "Spam"
    end
    redirect_to invoice_url
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  require 'nokogiri'
require 'open-uri'
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  def calculator
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  def product
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  def persona
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  def wall
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  def distributor
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.json
  def new
    @order = Order.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(params[:order])

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render json: @order, status: :created, location: @order }
      else
        format.html { render action: "new" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /orders/1
  # PUT /orders/1.json
  def update
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	require 'open-uri'

	def flash_class(type)
		case type
		when :alert
			"alert-error"
		when :notice
			"alert-success"
		else
			""
		end
	end

	def banamex_parser
		url = "http://portal.banamex.com.mx/c719_004/economiaFinanzas/es/home?xhost=http://www.banamex.com/"
   	doc = Nokogiri::HTML(open(url))
   	data_array = doc.css("td")
   	dolar = data_array[4].text.gsub(/\s+/, "")
 	end
 	
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/contact/contact.html.erb
<!--=== Breadcrumbs ===-->
<div class="breadcrumbs margin-bottom-40">
  <div class="container">
        <h1 class="color-green pull-left">Contáctanos</h1>
    </div><!--/container-->
</div><!--/breadcrumbs-->
<!--=== End Breadcrumbs ===-->

<!--=== Content Part ===-->
<div class="container">   
  <div class="row-fluid">
    <div class="span9">
      <!-- <div id="map" class="map map-box map-box-space margin-bottom-40">
      </div> -->
      <p>¿Tienes alguna duda o sugerencia?</p><br />
        <%= form_tag dispatch_email_path, method: :post do %>
        <label><%= label_tag "user_info[name]", "Nombre:", :input_html => {:style => 'width: 100%'} %></label>
        <%= text_field_tag("user_info[name]", value = nil, options = {:class => "span7"}) %>

        <label><%= label_tag "user_info[email]", "Correo:" %></label>
        <%= text_field_tag("user_info[email]", value = nil, options = {:class => "span7"}) %>

        <label><%= label_tag "user_info[message]", "Mensaje:" %></label>
        <%= text_area_tag("user_info[message]", value = nil, options = {:rows => 8, :class => "span10"}) %>

        <%= hidden_field "user_info[nickname]", "Seudonimo:" %> <!-- Anti spam, only bots fill this field -->
        <%= hidden_field_tag "user_info[nickname]"  %><br />
        
        <p><%= submit_tag "Enviar", class: "btn-u"%></p>
        <% end %>
     
    </div><!--/span9-->

    <div class="span3">
            <!-- Contacts -->
            <div class="headline"><h3>Contacto</h3></div>
            <ul class="unstyled who margin-bottom-20">
                <li><a href="#"><i class="icon-home"></i>Morelos 43 (Eje 6), Col. María del Carmen, Mexico, DF</a></li>
                <li><a href="#"><i class="icon-phone-sign"></i>+52 (55) 1204 0955</a></li>
                <li><a href="#"><i class="icon-globe"></i>http://www.greenbiani.com</a></li>
            </ul>
            <!-- Why we are? -->
        </div><!--/span3-->        
    </div><!--/row-fluid-->        
</div><!--/container-->   
<!--=== End Content Part ===-->


<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>


<script type="text/javascript">
    jQuery(document).ready(function() {
        App.init();
        App.initSliders();                
        Contact.initMap();        
    });
</script>

app/views/contact/invoice.html.erb


<!--=== Breadcrumbs ===-->
<div class="breadcrumbs margin-bottom-30">
  <div class="container">
    <h1 class="color-green pull-left">Cotizador</h1>
  </div><!--/container-->
</div><!--/breadcrumbs-->
<!--=== End Breadcrumbs ===-->



<div class="container">   
  <div class="row-fluid">
    <div class="span6">

      <div class="row-fluid">
        <h4>Favor de proporcionar la información requerida</h4>
      </div>
      <form id="ecot" action="#">
        <div class="row-fluid">
          <div class="span6">
            <label>Base</label>
            <input type="text" name="b" placeholder="en metros">
          </div>
          <div class="span6">
            <label>Altura</label>
            <input type="text" name="h" placeholder="en metros">
          </div>
        </div>
        <input type="text" name="d" placeholder="en metros" class="hideme" value=<%= banamex_parser %>>
        <div class="row-fluid">
          <div class="span6">
            <input type="button" class="btn-u" value="Calcular" onclick="cotizar();" />
          </div>
        </div><br>
        <div class="row-fluid">
          <div class="span6">
            <label>Area (m2)</label>
            <input type="text" name="a" readonly="readonly">
          </div>
        </div>
        <div class="row-fluid">
          <div class="span6">
            <label>Precio Total (MXN)</label>
            <input type="text" name="priceMxn" readonly="readonly">
          </div>
          <div class="span6">
            <label>Precio por metro (MXN)</label>
            <input type="text" name="priceMMxn" readonly="readonly">
          </div>
        </div>
        <div class="row-fluid">
          <div class="span6">
            <label>Precio Total (MXN) con IVA</label>
            <input type="text" name="priceMxnIva" readonly="readonly">
          </div>
          <div class="span6">
            <label>Precio por Metro (MXN) con IVA</label>
            <input type="text" name="priceMMxnIva" readonly="readonly">
          </div>
        </div>
        <div class="row-fluid">
          <div class="span6">
            <label>Precio Total (USD)</label>
            <input type="text" name="priceUsd" readonly="readonly">
          </div>
          <div class="span6">
            <label>Precio por Metro (USD)</label>
            <input type="text" name="priceMUsd" readonly="readonly"> <br>
          </div>
        </div>
        <div id="box"></div>
        <div id="box2"></div>
        <div id="box3"></div>
      </form>
    </div><!--/span6-->


    <div class="span6 hideme" id="invoicer">
      <div class="row-fluid">
        <h4>Solicitar cotización formal</h4>
      </div>
        <%= form_tag invoicer_email_path, method: :post do %>
        <label><%= label_tag "user_info[name]", "Nombre:", :input_html => {:style => 'width: 100%'} %></label>
        <%= text_field_tag("user_info[name]", value = nil, options = {:class => "span7"}) %>

        <label><%= label_tag "user_info[email]", "Correo:" %></label>
        <%= text_field_tag("user_info[email]", value = nil, options = {:class => "span7"}) %>

        <label><%= label_tag "user_info[message]", "Mensaje:" %></label>
        <%= text_area_tag("user_info[message]", value = nil, options = {:rows => 8, :class => "span10"}) %>

        <%= hidden_field_tag("user_info[base]", value = nil, options = {:id => "base"}) %>
        <%= hidden_field_tag("user_info[height]", value = nil, options = {:id => "height"}) %>
        <%= hidden_field_tag("user_info[area]", value = nil, options = {:id => "area"}) %>
        <%= hidden_field_tag("user_info[priceMxn]", value = nil, options = {:id => "priceMxn"}) %>

        <%= hidden_field "user_info[nickname]", "Seudonimo:" %>
        <%= hidden_field_tag "user_info[nickname]"  %><br />
        
        <p><%= submit_tag "Enviar", class: "btn-u"%></p>
        <% end %>
     
    </div><!--/span9-->

    </div>

  </div>
</div>



<script type="text/javascript" src="cotizador.js">
var i = #{banamex_parser};

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<head>
  <meta name="google-site-verification" content="8f_-80I9XcnHra5K51hzSm_QtrKuMMIBfun5bup5wi4" />
  <title>Biani</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8" />
  <meta content="width=device-width, initial-scale=1.0" name="viewport" />
  <link rel="shortcut icon" href="favicon.ico" />

  <!--=== Top ===-->    
<div class="top">
  <div class="container">         
    <ul class="loginbar pull-right">
      <!-- <li><i class="icon-globe"></i><a>Languages <i class="icon-sort-up"></i></a>
        <ul class="nav-list">
          <li class="active"><a href="#">English</a> <i class="icon-ok"></i></li>
          <li><a href="#">Spanish</a></li>
        </ul>
      </li> -->
      
    </ul>
  </div>      
</div><!--/top-->
<!--=== End Top ===-->    

<!--=== Header ===-->
<div class="header">               
  <div class="container"> 
    <!-- Logo -->       
    <div class="logo">                                             
        <a href="<%= '/' %>"><%= image_tag("logo1-default.png", :id => "logo-header", :alt => "logo") %></a>
    </div><!-- /logo -->        
                                
    <!-- Menu -->       
    <div class="navbar">                                
        <div class="navbar-inner">                                  
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a><!-- /nav-collapse -->                                  
            <div class="nav-collapse collapse">                                     
                <ul class="nav top-2">
                  <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Muro Verde
                            <b class="caret"></b>                            
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="<%= '/wall#what' %>">¿Qué es?</a></li>
                            <li><a href="<%= '/wall#why' %>">¿Por qué?</a></li>
                            <li><a href="<%= '/wall#choose' %>">Elígenos</a></li>
                        </ul>
                        <b class="caret-out"></b>                        
                    </li>
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Producto
                            <b class="caret"></b>                            
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="<%= '/product#modular' %>">Sistema Modular</a></li>
                            <li><a href="<%= '/product#instal' %>">Fácil Instalación</a></li>
                            <li><a href="<%= '/product#mant' %>">Mantenimiento Mínimo</a></li>
                        </ul>
                        <b class="caret-out"></b>                        
                    </li>
                    <li>
                        <a href="" class="dropdown-toggle" data-toggle="dropdown">A quien
                            <b class="caret"></b>                            
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="<%= '/persona#arch' %>">Arquitectos</a></li>
                            <li><a href="<%= '/persona#di' %>">Diseñadores de Interiores</a></li>
                            <li><a href="<%= '/persona#ent' %>">Emprendedores</a></li>
                            <li><a href="<%= '/persona#nature' %>">Amantes de la Naturaleza</a></li>
                        </ul>
                        <b class="caret-out"></b>                        
                    </li>
                    <li>
                        <a href="" class="dropdown-toggle" data-toggle="dropdown">Comprar
                            <b class="caret"></b>                            
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="<%= '/invoice' %>">Cotizar</a></li>
                            <li><a href="<%= '/distributor' %>">Distribuidores</a></li>
                        </ul>
                        <b class="caret-out"></b>                        
                    </li>
                   <!--  <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Galeria
                            <b class="caret"></b>                            
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="portfolio.html">Portfolio</a></li>
                            <li><a href="portfolio_item.html">Portfolio Item</a></li>
                            <li><a href="portfolio_2columns.html">Portfolio 2 Columns</a></li>
                            <li><a href="portfolio_3columns.html">Portfolio 3 Columns</a></li>
                            <li><a href="portfolio_4columns.html">Portfolio 4 Columns</a></li>
                        </ul>
                        <b class="caret-out"></b>                        
                    </li> -->
                    <li>
                      <a href="<%= '/contact' %>">Contacto                        
                      </a>                    
                    </li>
                                             
                </ul>
                <div class="search-open">
                    <div class="input-append">
                        <form>
                            <input type="text" class="span3" placeholder="Search" />
                            <button type="submit" class="btn-u">Go</button>
                        </form>
                    </div>
                </div>
            </div><!-- /nav-collapse -->                                
        </div><!-- /navbar-inner -->
    </div><!-- /navbar -->                          
  </div><!-- /container -->               
</div><!--/header -->      
<!--=== End Header ===-->

<!--=== Body ===-->
<div class="container">
  <% flash.each do |type, message| %>
  <div class="alert <%= flash_class type %>">
    <button class="close" data-dismiss="alert">x</button>
    <%= message %>
  </div>
  <% end %>
</div>

<%= yield %>

<!--=== End Body ===-->

<!--=== Footer ===-->
<div class="footer">
  <div class="container">
    <div class="row-fluid">
      <div class="span4">
        <div class="headline"><h3>Biani</h3></div>  
          <p class="margin-bottom-25">Mucha Gente pequeña, en lugares pequeños, haciendo cosas pequeñas, puede cambiar el mundo. Únete a un mundo más verde.</p>  
      </div><!--/span4--> 
    
      <div class="span4">
        <div class="headline"><h3>Síguenos</h3></div> 
          <ul class="social-icons">
              <!-- <li><a href="#" data-original-title="Feed" class="social_rss"></a></li> -->
              <li><a href="https://www.facebook.com/Biani.MurosVerdes" data-original-title="Facebook" class="social_facebook"></a></li>
              <!-- <li><a href="#" data-original-title="Twitter" class="social_twitter"></a></li> -->
              <!-- <li><a href="#" data-original-title="Goole Plus" class="social_googleplus"></a></li>
              <li><a href="#" data-original-title="Pinterest" class="social_pintrest"></a></li>
              <li><a href="#" data-original-title="Linkedin" class="social_linkedin"></a></li>
              <li><a href="#" data-original-title="Vimeo" class="social_vimeo"></a></li> -->
          </ul>
      </div><!--/span4-->
      <div class="span4">
        <div class="headline"><h3>Contacto</h3></div> 
          <address>
            Morelos 43 (Eje 6) <br />
            Col. María del Carmen <br />
            México, DF <br />
            Tel: +52 (55) 1204 0955 <br />
            <!-- Email: <a href="mailto:info@anybiz.com" class="">info@anybiz.com</a> -->
          </address>   
      </div><!--/span4-->
    </div><!--/row-fluid--> 
  </div><!--/container--> 
</div><!--/footer-->  
<!--=== End Footer ===-->

<!--=== Copyright ===-->
<div class="copyright">
  <div class="container">
    <div class="row-fluid">
      <div class="span8">           
              
      </div>
      <div class="span4"> 
        <p>2013 &copy; Biani. Todos los derechos reservados. <!-- <a href="#">Privacy Policy</a> | <a href="#">Terms of Service</a> --></p>
      </div>
    </div><!--/row-fluid-->
  </div><!--/container--> 
</div><!--/copyright--> 
<!--=== End Copyright ===-->

<!-- begin olark code -->
<script data-cfasync="false" type='text/javascript'>/*<![CDATA[*/window.olark||(function(c){var f=window,d=document,l=f.location.protocol=="https:"?"https:":"http:",z=c.name,r="load";var nt=function(){
f[z]=function(){
(a.s=a.s||[]).push(arguments)};var a=f[z]._={
},q=c.methods.length;while(q--){(function(n){f[z][n]=function(){
f[z]("call",n,arguments)}})(c.methods[q])}a.l=c.loader;a.i=nt;a.p={
0:+new Date};a.P=function(u){
a.p[u]=new Date-a.p[0]};function s(){
a.P(r);f[z](r)}f.addEventListener?f.addEventListener(r,s,false):f.attachEvent("on"+r,s);var ld=function(){function p(hd){
hd="head";return["<",hd,"></",hd,"><",i,' onl' + 'oad="var d=',g,";d.getElementsByTagName('head')[0].",j,"(d.",h,"('script')).",k,"='",l,"//",a.l,"'",'"',"></",i,">"].join("")}var i="body",m=d[i];if(!m){
return setTimeout(ld,100)}a.P(1);var j="appendChild",h="createElement",k="src",n=d[h]("div"),v=n[j](d[h](z)),b=d[h]("iframe"),g="document",e="domain",o;n.style.display="none";m.insertBefore(n,m.firstChild).id=z;b.frameBorder="0";b.id=z+"-loader";if(/MSIE[ ]+6/.test(navigator.userAgent)){
b.src="javascript:false"}b.allowTransparency="true";v[j](b);try{
b.contentWindow[g].open()}catch(w){
c[e]=d[e];o="javascript:var d="+g+".open();d.domain='"+d.domain+"';";b[k]=o+"void(0);"}try{
var t=b.contentWindow[g];t.write(p());t.close()}catch(x){
b[k]=o+'d.write("'+p().replace(/"/g,String.fromCharCode(92)+'"')+'");d.close();'}a.P(2)};ld()};nt()})({
loader: "static.olark.com/jsclient/loader0.js",name:"olark",methods:["configure","extend","declare","identify"]});
/* custom configuration goes here (www.olark.com/documentation) */
olark.identify('7475-141-10-9172');/*]]>*/</script><noscript><a href="https://www.olark.com/site/7475-141-10-9172/contact" title="Contact us" target="_blank">Questions? Feedback?</a> powered by <a href="http://www.olark.com?welcome" title="Olark live chat software">Olark live chat software</a></noscript>
<!-- end olark code -->

  </body>
</html>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :height %><br />
    <%= f.number_field :height %>
  </div>
  <div class="field">
    <%= f.label :width %><br />
    <%= f.number_field :width %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/calculator.erb
<div class="container">

  <h1>Cotizador</h1>

  <form id="ecot" action="#">
    <fieldset>
      <legend>Calculadora</legend>
      <label>Altura</label>
      <input type="text" name="h" placeholder="en metros">
      <label>Base</label>
      <input type="text" name="b" placeholder="en metros"><br><br>
      <label>Area (m2)</label>
      <input type="text" name="a" readonly="readonly">

      <label>Número de plantas</label>
      <input type="text" name="a" readonly="readonly">

      


      <label>Flujo (litros por hora)</label>
      <input type="text" name="a" readonly="readonly">

      <label>Consumo de agua (litros por día)</label>
      <input type="text" name="a" readonly="readonly">

      



       <br>
      
      <input type="button" class="btn" value="Calcular" onclick="cotizar();" />
    </fieldset>
  </form>
</div>

<script type="text/javascript" src="calculator.js">
</script>

app/views/orders/distributor.erb
<!--=== Content Part ===-->
<!--=== Breadcrumbs ===-->
<div class="breadcrumbs margin-bottom-40">
  <div class="container">
        <h1 class="color-green pull-left">Distribuidores</h1>
    </div><!--/container-->
</div><!--/breadcrumbs-->
<!--=== End Breadcrumbs ===-->

<!--=== Content Part ===-->
<div class="container">   
  <h3>¿Quieres distribuir muros verdes?</h3></br>
<p>Únete a nuestro grupo para colaborar con nuestro empeño de un mundo más verde, y no solo eso aumenta tus ingresos significativamente, contáctanos, nosotros te asesoramos por medio de videos, contactos y textos para que tu negocio sea todo un éxito. </p></br></br>

<a href="<%= '/contact' %>" class="btn-u btn-u-large btn-u-green one-page-btn"><i class="icon-external-link"></i> Contáctanos</a></br></br></br></br></br></br></br>

      
</div><!--/container-->   

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Height:</b>
  <%= @order.height %>
</p>

<p>
  <b>Width:</b>
  <%= @order.width %>
</p>


<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>